project_id = "xkoncobtixlrtvgpdqtq"

[functions.validate-admin-password]
verify_jwt = false

[functions.check-promotional-access]
verify_jwt = false

[functions.manage-promotional-access]
verify_jwt = false