// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkoncobtixlrtvgpdqtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhrb25jb2J0aXhscnR2Z3BkcXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0NTcxOTcsImV4cCI6MjA1NDAzMzE5N30.3XxfzXYZaiutQyGevzbL3OR8VXv10tnwI_JBLG6utFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);